baseurl = "http://www.claykom.com"
title = "Clayton K. Blog"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[services]

[services.disqus]
  shortname = 'wontdisappoint'


[params]
author = "Clayton Kominik"
info = "Software & Automation Developer"
description = "Clayton Kominik's personal website"

faviconSVG = "/img/favicon.svg"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2021

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

# Social Links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/claykom/"

[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://x.com/wontdisappoint_"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"